### ISSUE TITLE
Enhancement: for opening the url in same window

### ISSUE THREAD

**Issue by rahulravindran0108** [Simran-B/gitbook-plugin-toolbar#1]
I would love to route the link in the same target window. Maybe have another property in the json for this ?

``` javascript
window.open(button.url.replace(re, function(matched) {
                        return mapping[matched];
                    }), button.window ? "_self" : "_blank");
```

**Comment by Simran-B** [comment]
This should do: https://github.com/Simran-B/gitbook-plugin-toolbar/commit/e5374eca0b7f8eb61de6fc0ce27085a6be01c519

In `book.json`, you can set a `target` for every link. Set this to `_self` to make it change the browser location instead of opening a new window / tab.

**Comment by rahulravindran0108** [comment]
@Simran-B Thanks
